### ISSUE TITLE
Fault switches not working

### ISSUE THREAD

**Issue by Prince-Joy** [AUCOHL/Fault#14]
@donn 
I am facing issues with fault, after completion of the installation procedure, when I am trying to get version using fault --version/-V
It's showing me the help menu every time, not only that,  only subcommand are working like
1. fault synth --top xyz -l xyz.lib xyz.v > its working
2. fault cut xyz.netlist.v > its also working but when I am trying to run **fault --cellModel xyz.v filename** its not working instead showing help menu every time.
![image](https://user-images.githubusercontent.com/63585739/107624125-9cf95180-6c84-11eb-9e13-75e7c39305c5.png)
![image](https://user-images.githubusercontent.com/63585739/107624239-c6b27880-6c84-11eb-9c17-6b912c689c87.png)

**Comment by donn** [comment]
If you check the resulting help menu, you will notice that one other option is required, namely --clock. 

Please add the missing option and retry.

**Comment by Prince-Joy** [comment]
Thank you very much @donn 
facing another problem when running can you please look into it.
![image](https://user-images.githubusercontent.com/63585739/107732981-ffedf580-6d23-11eb-8e3d-061f840554c6.png)
after that I have tried to install **iverilog** using the given make file **iverilog_build.swift** but showing the following errors
![image](https://user-images.githubusercontent.com/63585739/107733145-70951200-6d24-11eb-9b33-7c257e728715.png)

**Comment by Prince-Joy** [comment]
Thank you so much @donn , I am facing another issue can you please look into it.
![image](https://user-images.githubusercontent.com/63585739/107739274-b78a0400-6d32-11eb-9bb6-e130ac169476.png)

**Comment by donn** [comment]
For the first issue, try updating IcarusVerilog, I recall having this issue myself with older versions.

Tap is @Manarabdelaty territory. Manar?

**Comment by Manarabdelaty** [comment]
@Prince-Joy Can you make sure of the following ? 
- if the reset signal is asynchronous, you will need to add it to the ignored inputs during simulation; using `--ignoring`.This is because generating a test pattern for an asynchronous reset could arbitrarily reset the circuit if it is set to either 0 or  1. (You will need to specify the --ignoring for the main option and and both the chain and tap sub-commands)

If this is not the case with your design, can you post the chained.v file and .bin files ?

**Comment by Prince-Joy** [comment]
@donn In my code reset is synchronous,
![image](https://user-images.githubusercontent.com/63585739/107902821-ba266c80-6f71-11eb-966e-7c2cebd4483a.png)
reference: asic-world
After running the following commands
![image](https://user-images.githubusercontent.com/63585739/107902889-ec37ce80-6f71-11eb-8006-6bbdbb98773c.png)
I got the **error**:
![image](https://user-images.githubusercontent.com/63585739/107902957-21dcb780-6f72-11eb-8fc4-89b6e169a184.png)

**Comment by PiyushSaini97** [comment]
@Prince-Joy I'm facing similar issues. When I try to run anything using osu035, I get the same at Test Vector generation. This is bypassed when nangate is used. However, at `fault asm` I encounter the mismatch of json and scan chain registers. I tried ignoring clock and reset with the help of `fault -i` command but the same error. Also, there seems to be a mismatch of just 1 input and scan register each time.

**Comment by PiyushSaini97** [comment]
@Prince-Joy I found the reason for mismatch. Please ensure that you ignore your reset signal for TV generation step by appending `-i reset` option to `fault` command (your clock automatically gets ignored when `--clock` command is used. While running `fault chain` command, you are ignoring reset and clock using `--reset` and `--clock` respectively. If you had not ignored this at TV generation step then you basically got one extra test vector input as compared to the total scan chain register. 

@donn please verify whether this explanation is correct or not.

**Comment by donn** [comment]
That's actually correct, yeah. You're supposed to add the reset to `-i`.

Maybe for consistency, I should add the `--reset` option to the `fault` command.

**Comment by PiyushSaini97** [comment]
But wouldn't that cause issue for the designs that don't necessarily use reset?
For example, in the folder /Benchmarks/ISCAS_89, some of the designs don't use reset. I tried running s298.v. 
The module does not contain reset(or none of the inputs resemble a reset signal).

![s298](https://user-images.githubusercontent.com/85390797/124020039-6a6bad80-da07-11eb-89d4-5c4090b8dacf.png)

I tried creating TV for the same but ran into an error. And without much idea I cant consider any of the input as reset.
![error_s298](https://user-images.githubusercontent.com/85390797/124020229-a43cb400-da07-11eb-918f-deaf1f41b869.png)

Please clarify if I misunderstood.

**Comment by donn** [comment]
Good point, though the thing is I don't think it would be easy to make scan chains that cannot be reset. I'll have to discuss with the team whether we want to support no-reset designs.

**Comment by donn** [comment]
So, I've decided to make most commands take `--clock` and `--reset`. There'll be an update in the future where we'll create the reset port if it doesn't exist.
