### ISSUE TITLE
Swift not found

### ISSUE THREAD

**Issue by IshaShah2806** [AUCOHL/Fault#20]
I was installing Fault and I had already installed Swift in my Ubuntu 20.04 yet while installing Fault I faced an error SWIFT not found.
![Capture](https://user-images.githubusercontent.com/86776089/124105718-21f0d600-da81-11eb-8a3c-483742055dbf.PNG)

**Comment by donn** [comment]
Are you using WSL or WSL2?

At any rate it's curious that `sh` drops PATH. Can you replace `let compilationResult = "swift build".shOutput()` with `let compilationResult = "echo $PATH".shOutput() && false` and let me know the output?

**Comment by IshaShah2806** [comment]
Thank you for your time .I am using WSL 2  and I made the necessary changes and I got this output.
![Capture](https://user-images.githubusercontent.com/86776089/124147255-27afe100-daac-11eb-88c0-056345afe4a5.PNG)

**Comment by donn** [comment]
Ah. Gotcha, always need to confirm no one is using WSL1. It's too unpredictable. :)

The issue is your PATH has a literal tilde, not your home folder. Can you replace `~/swift-5.3.3-RELEASE-ubuntu20.04/usr/bin` with an absolute path where you're setting the PATH variable? In this case, it would be `/home/isha/swift-5.3.3-RELEASE-ubuntu20.04/usr/bin`.

**Comment by IshaShah2806** [comment]
I replaced as directed .But still the same error
![Capture](https://user-images.githubusercontent.com/86776089/124152133-e2da7900-dab0-11eb-8690-0d1a8b71253f.PNG)
![Capture](https://user-images.githubusercontent.com/86776089/124152370-16b59e80-dab1-11eb-95ec-e131a32e7fe9.PNG)

**Comment by donn** [comment]
That's so weird. I'll have to come back to this later- we'll probably need a workaround.

**Comment by RameenAnwar** [comment]
try `export PATH=home/isha/Fault/swift-5.3.3-RELEASE-ubuntu20.04/usr/bin`
then `swift ./install.swift`

**Comment by donn** [comment]
For future searchers: please use the AppImage.
