### ISSUE TITLE
Missing external test set example file s27.v.tv.json

### ISSUE THREAD

**Issue by padiyarsandesh** [AUCOHL/Fault#30]
Hi,
The external test vector example file s27.v.tv.json ( PATH :RTL/ISCAS_89/s27.v.tv.json) is missing. 
Would appreciate if the file would be availabl
![Screenshot from 2022-06-27 00-34-20](https://user-images.githubusercontent.com/66885202/175885200-b2eed3ab-5406-4bcb-a7d1-dc4355ac236a.png)
e as I want to use external test set for my research purposes.
The link is broken.

Thanks

**Comment by donn** [comment]
Do we link to that anywhere?

**Comment by padiyarsandesh** [comment]
Yeah , its there is the wiki usage , under section: 2)Input TV Set a)JSON Format
![Screenshot 2022-06-27 224244](https://user-images.githubusercontent.com/66885202/175997946-90ef06e5-a839-4467-8ca2-a7f355589baa.png)

**Comment by priyajit99** [comment]
Same issue here . @donn pls look into the issue for example test pattern json file.

**Comment by cmarqu** [comment]
The file apparently got lost in https://github.com/AUCOHL/Fault/commit/cd066bc1478ab8cf6795c2df3442316b5e7960d5 but can be extracted from the history: https://github.com/AUCOHL/Fault/blob/432adf445acef670fed994950fcf92c8cf8cfefa/RTL/ISCAS_89/s27.v.tv.json

**Comment by priyajit99** [comment]
On the file it is showing invalid file

**Comment by donn** [comment]
Well, for various reasons, the vector format may or may not have changed. I would assume this is an issue of outdated documentation and not an issue of the file being invalid.

I will update the documentation.
