### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by visionvlsi** [AUCOHL/Fault#31]
when I am using the following command , I am getting compilation terminated 

swift iverilog_build.swift 

------------------
parse.cc:465:10: fatal error: parse.hh: No such file or directory
  465 | #include "parse.hh"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:245: parse.o] Error 1
![Screenshot from 2022-12-07 19-02-37](https://user-images.githubusercontent.com/98731221/206193347-cc053a5e-deff-4736-a31a-2a5bca6374d9.png)

**Comment by donn** [comment]
Compiling IcarusVerilog has always been a bit hit or miss. Is there a reason you're not using Ubuntu 20.04?
