### ISSUE TITLE
Invalid Test Vector File

### ISSUE THREAD

**Issue by priyajit99** [AUCOHL/Fault#34]
For circuit s27 , I am writing my own test vector file as given in s27.v.tv.json

But will running the tool, it is showing invalid test vector file. @cmarqu can  look into the issue??
![fault](https://user-images.githubusercontent.com/106911897/211731725-cdb8b349-9001-418e-a238-7a7b42c32c65.jpg)

**Comment by donn** [comment]
Can you please refrain from @'ing contributors and/or community members to ask for help? It's very likely to cause the exact opposite to happen.

Also, it could very well be that your file is invalid. This might not an issue with the tool. If you'd like help, kindly upload the relevant file.
