### ISSUE TITLE
Errors reproducing examples in the Wiki

### ISSUE THREAD

**Issue by Coloquinte** [AUCOHL/Fault#49]
I used the docker image to run the example in the Wiki. There are minor changes to be made with the Wiki example usage:
* the generated netlist now ends with `nl.v` everywhere, not `netlist.v`,
* the simulations run requires a clock argument (`fault -c Tech/osu035/osu035_stdcells.v -v 100 -r 50 -m 95 --ceiling 1000 Netlists/s27.nl.v.cut.v  --clock CK`)
* the bench export command complains about the presence of inout ports on PADINOUT (workaround is to remove it from the library).
* the command errors out with the help message when using the --bench argument for Atalanta: `fault -g atalanta -c Tech/osu035/osu035_stdcells.v -b Netlists/s27.nl.v.cut.v.bench Netlists/s27.nl.v.cut.v`

**Comment by donn** [comment]
Looking into them- I'll also just move the documentation to just readthedocs because it turns out GitHub wikis aren't great

**Comment by donn** [comment]
I have went ahead and updated the example document and verified it works: https://fault.readthedocs.io/en/latest/usage.html
